---
- name: V-38649 Low  The system default umask for the csh shell must be 077
  replace: backup=yes dest=/etc/csh.cshrc regexp="umask \d\d\d" replace="umask 077"
  tags: [ 'cat3' , 'V-38649' , 'csh' , 'umask' ]

- name: V-38642 Low  The system default umask for daemons must be 027 or 022
  lineinfile: state=present backup=yes dest=/etc/init.d/functions regexp="umask \d\d\d" line="umask 022"
  tags: [ 'cat3' , 'V-38642' , 'umask' ]

- name: "V-38648 Low  The qpidd service must not be running\n    V-38641 Low  The atd service must be disabled\n    V-38640 Low  The Automatic Bug Reporting Tool (abrtd) service must not be running\n    V-38646 Low  The oddjobd service must not be running\n    V-38644 Low  The ntpdate service must not be running\n    V-38650 Low  The rdisc service must not be running\n    V-38437 Low  Automated file system mounting tools must not be enabled unless needed\n    V-38669 Low  The postfix service must be enabled for mail delivery\n    V-38672 Low  The netconsole service must be disabled unless required"
  service: name={{ item.name }} state={{ item.state }} enabled={{ item.enabled }}
  when: "'{{ item.name }}' in sysv_services.stdout_lines and '{{ item.name }}' != 'rhnsd'"
  with_items: '{{ rhel6stig_cat3_services }}'
  tags: [ 'cat3' , 'V-38640' , 'abrtd', 'V-38648' , 'qpidd' , 'V-38641' , 'atd' , 'V-38646' , 'oddjobd' , 'V-38644' , 'ntpdate' , 'V-38650' , 'rdisc' , 'V-38437' , 'autofs' , 'V-38669' , 'postfix' , 'V-38672' , 'netconsole' , 'V-38478' , 'rhnsd' ]

- name: V-38478 Low check if rhnsd exists
  stat: path='/etc/init.d/rhnsd'
  register: rhnsd_check
  tags: [ 'cat3' , 'V-38478' , 'rhnsd' ]

- name: V-38478 Low  The Red Hat Network Service (rhnsd) service must not be running, unless using RHN or an RHN Satellite
  shell: "chkconfig rhnsd off && service rhnsd stop"
  register: result
  when: rhnsd_check.stat.exists
  failed_when: result.rc != 0 and result.rc != 6
  tags: [ 'cat3' , 'V-38478' , 'rhnsd' ]

- name: V-38647 Low  The system default umask in /etc/profile must be 077
  replace: backup=yes dest={{ item }} regexp="umask \d\d\d" replace="umask 077"
  with_items:
    - /etc/profile
    - /etc/bashrc
  tags: [ 'cat3' , 'V-38647' , 'umask' , 'bash' ]


# Set default umask for fish shell if it is installed
# This required two tasks in order to add multiple lines cleanly
# Adding '\n' to the 'line' field causes this module to reinsert the same
# line every time the task is run which is very undesirable.
- name: Set default umask for fish shell to 077
  lineinfile: backup=yes dest=/etc/fish/config.fish line="# Set default umask" insertafter=EOF
  when: '"fish" in shells.stdout_lines'
  tags: [ 'cat3' , 'V-38647' , 'umask' , 'bash' ]

- name: Set default umask for fish shell to 077
  lineinfile: backup=yes dest=/etc/fish/config.fish line="umask 077" insertafter="# Set default umask"
  when: '"fish" in shells.stdout_lines'
  tags: [ 'cat3' , 'V-38647' , 'umask' , 'bash' ]


- name: V-38645 Low  The system default umask in /etc/login.defs must be 077
  lineinfile: "state=present backup=yes dest=/etc/login.defs regexp='^UMASK' line='UMASK           077'"
  tags: [ 'cat3' , 'V-38645' , 'umask' ]

- name: V-51369 Low  The system must use a Linux Security Module configured to limit the privileges of system services
  selinux: policy=targeted state=enforcing
  tags: [ 'cat3' , 'V-51369' , 'selinux' ]


- name: Check permissions on all files and directories associated with packages
  shell: "grep '^.M' /tmp/rhel6stig_rpm_verify | awk '{print $2}' "
  changed_when: false
  register: rpm_file_permissions_check
  failed_when: rpm_file_permissions_check.stderr
  tags: [ 'cat3' , 'V-38452' , 'rpm' ]

# - name: V-38452 Low  The system package management tool must verify permissions on all files and directories associated with packages
#   shell: rpm --setperms $(rpm -qf {{ item }})
#   when: rpm_file_permissions_check.stdout
#   with_items: rpm_file_permissions_check.stdout_lines
#   tags: [ 'cat3' , 'V-38452' , 'rpm' ]


- name: Check group-ownership on all files and directories associated with packages
  shell: "grep '^......G' /tmp/rhel6stig_rpm_verify | awk '{print $3}' "
  changed_when: false
  register: rpm_group_ownership_check
  failed_when: rpm_group_ownership_check.stderr
  tags: [ 'cat3' , 'V-38453' , 'rpm' ]

# - name: V-38453 Low  The system package management tool must verify group-ownership on all files and directories associated with packages
#   shell: rpm --setugids $(rpm -qf {{ item }})
#   when: rpm_group_ownership_check.stdout
#   with_items: rpm_group_ownership_check.stdout_lines
#   tags: [ 'cat3' , 'V-38453' , 'rpm' ]


- name: V-38608 Low  The SSH daemon must set a timeout interval on idle sessions
  lineinfile: "state=present backup=yes dest=/etc/ssh/sshd_config regexp='^(#)?ClientAliveInterval' line='ClientAliveInterval 900'"
  tags: [ 'cat3' , 'V-38608' , 'ssh' ]
  notify: restart ssh


- name: Checking integrity of installed files associated with packages
  shell: "awk '$1 ~ /..5/ && $2 != \"c\" ' /tmp/rhel6stig_rpm_verify | awk '{print $2}' "
  changed_when: false
  register: rpm_integrity_check
  failed_when: rpm_integrity_check.stderr
  tags: [ 'cat3' , 'V-38447' , 'rpm' ]

# - name: V-38447 Low  The system package management tool must verify contents of all files associated with packages
#   shell: yum reinstall -y $(rpm -qf {{ item }})
#   when: rpm_integrity_check.stdout
#   with_items: rpm_integrity_check.stdout_lines
#   tags: [ 'cat3' , 'V-38447' , 'rpm' ]


# - name: V-38659 Low  The operating system must employ cryptographic mechanisms to protect information in storage

- name: V-38651 Low  The system default umask for the bash shell must be 077
  replace: backup=yes dest=/etc/bashrc regexp="umask \d\d\d" replace="umask 077"
  tags: [ 'cat3' , 'V-38651' , 'umask' ]

- name: V-38656 Low  The system must use SMB client signing for connecting to samba servers using smbclient
  lineinfile: "state=present backup=yes dest=/etc/samba/smb.conf regexp='client signing' line='client signing = mandatory' insertafter='\\[global\\]'"
  when: samba_check.stat.exists
  tags: [ 'cat3' , 'V-38656' , 'smb' ]
  notify: restart samba

# - name: V-38657 Low  The system must use SMB client signing for connecting to samba servers using mount.cifs

- name: V-51379 Low  All device files must be monitored by the system Linux Security Module
  command: restorecon -r /dev/
  when: rhel6stig_dev_unlabeled_context.stdout
  tags: [ 'cat3' , 'V-51379' , 'secontext' ]

- name: V-38480  Low Users must be warned 7 days in advance of password expiration
  lineinfile: "state=present backup=yes dest=/etc/login.defs regexp='^#?PASS_WARN_AGE' line='PASS_WARN_AGE\t7'"
  tags: [ 'cat3' , 'V-38480' , 'passwords' ]

- name: V-38528 Low  The system must log Martian packets
  sysctl: name=net.ipv4.conf.all.log_martians value=1 state=present reload=yes ignoreerrors=yes
  tags: [ 'cat3' , 'V-38528' , 'martian_packets' , 'kernel_parameters' ]

# - name: V-38661 Low  The operating system must protect the confidentiality and integrity of data at rest
# - name: V-38662 Low  The operating system must employ cryptographic mechanisms to prevent unauthorized disclosure of data at rest unless otherwise protected by alternative physical measures
# - name: V-38467 Low The system must use a separate file system for the system audit data path
# - name: V-38463 Low The system must use a separate file system for /var/log

- name: V-38460 Low  The NFS server must not have the all_squash option enabled
  replace: backup=yes dest=/etc/exports regexp=',?all_squash'
  tags: [ 'cat3' , 'V-38469' , 'nfs' ]
  notify: restart nfs

- name: V-38702 Low  The FTP daemon must be configured for logging or verbose mode
  lineinfile: "state=present backup=yes dest=/etc/vsftpd/vsftpd.conf regexp='^#?xferlog_enable=' line='xferlog_enable=YES'"
  when: "'vsftpd' in sysv_services.stdout"
  tags: [ 'cat3' , 'V-38702' , 'vsftp' ]
  notify: restart vsftpd

- name: V-38494 Low The system must prevent the root account from logging in from serial consoles
  lineinfile: state=absent dest=/etc/securetty regexp='^ttyS[0-9]' backup=yes
  tags: [ 'cat3' , 'V-38494' , 'root_access' , 'tty' ]

- name: V-38676 Low  The xorg-x11-server-common (X Windows) package must not be installed, unless required
  yum: name="@X Window System" state=absent
  when: not rhel6stig_xwindows_required
  tags: [ 'cat3' , 'V-38676' , 'xwindows' ]

- name: V-38675 Low  Process core dumps must be disabled unless needed
  lineinfile: "state=present backup=yes dest=/etc/security/limits.conf regexp='^#?\\*.*(hard|soft).*core' line='*               hard    core            0'"
  tags: [ 'cat3' , 'V-38675' , 'core_dump' ]

- name: V-38474 Low  The system must allow locking of graphical desktop sessions
  command: gconftool-2 --direct --config-source xml:readwrite:/etc/gconf/gconf.xml.mandatory --type string --set /apps/gnome_settings_daemon/keybindings/screensaver "<Ctrl><Alt>l"
  when: rhel6stig_xwindows_required
  tags: [ 'cat2' , 'V-38474' , 'gui' , 'screen_lock' ]

- name: V-38471 Low The system must forward audit records to the syslog service
  lineinfile: "state=present backup=yes dest=/etc/audisp/plugins.d/syslog.conf regexp='^active' line='active = yes'"
  tags: [ 'cat3' , 'V-38471' , 'auditd' ]
  notify: restart auditd

# - name: V-38473 Low  The system must use a separate file system for user home directories


- name: Check ownership on all files and directories associated with packages
  shell: "grep '^.....U' /tmp/rhel6stig_rpm_verify | awk '{print $2}' "
  changed_when: false
  register: rpm_file_ownership_check
  failed_when: rpm_file_ownership_check.stderr
  tags: [ 'cat3' , 'V-38454' , 'rpm' ]

# - name: V-38454 Low  The system package management tool must verify ownership on all files and directories associated with packages
#   shell: rpm --setugids $(rpm -qf {{ item }})
#   when: rpm_file_ownership_check.stdout
#   with_items: rpm_file_ownership_check.stdout_lines
#   tags: [ 'cat3' , 'V-38454' , 'rpm' ]

- name: V-38687 Low  The system must provide VPN connectivity for communications over untrusted networks
  yum: name=openswan state=present
  tags: [ 'cat3' , 'V-38687' , 'openswan' , 'vpn' ]

- name: V-38685 Low  Temporary accounts must be provisioned with an expiration date
  command: chage -E {{ item.expiration }}  {{ item.user }}
  when: rhel6stig_temporary_users is defined
  with_items: '{{ rhel6stig_temporary_users }}'
  tags: [ 'cat3' , 'V-38685' , 'accounts' ]

- name: V-38684 Low  The system must limit users to 10 simultaneous system logins, or a site-defined number, in accordance with operational requirements
  lineinfile: "state=present backup=yes dest=/etc/security/limits.conf insertbefore='^# End of file' regexp='^#?\\*.*maxlogins' line='*               hard    maxlogins       {{ rhel6stig_maxlogins }}'"
  tags: [ 'cat3' , 'V-38684' , 'logon_settings' ]


# Check for duplicate account names and show the output if any are found
- name: Checking for duplicate account names
  command: pwck -rq
  changed_when: false
  failed_when: dup_account_check.stderr
  register: dup_account_check
  tags: [ 'cat3' , 'V-38683' , 'accounts' ]

- name: The following duplicate entries were found in /etc/passwd. This is a finding.
  debug: var=dup_account_check.stdout_lines
  when: dup_account_check.stdout_lines
  tags: [ 'cat3' , 'V-38683' , 'accounts' ]

- name: V-38683 Low  All accounts on the system must have unique user or account names
  pause: prompt="Duplicate account names were found in /etc/passwd. This is a finding. Press Enter to continue"
  when: dup_account_check.stdout_lines and not rhel6stig_fullauto
  tags: [ 'cat3' , 'V-38683' , 'accounts' ]


# Check for missing groups and show the output if any are found
- name: Checking for missing groups
  shell: pwck -r | grep 'no group'
  changed_when: false
  failed_when: missing_group_check.stderr
  register: missing_group_check
  tags: [ 'cat3' , 'V-38681' , 'accounts' ]

- name: The following groups in /etc/passwd are missing from /etc/group. This is a finding.
  debug: var=missing_group_check.stdout_lines
  when: missing_group_check.stdout_lines
  tags: [ 'cat3' , 'V-38681' , 'accounts' ]

- name: V-38681 Low  All GIDs referenced in /etc/passwd must be defined in /etc/group
  pause: prompt="Groups defiend in /etc/passwd are missing from /etc/group. This is a finding. Press Enter to continue"
  when: missing_group_check.stdout_lines and not rhel6stig_fullauto
  tags: [ 'cat3' , 'V-38681' , 'accounts' ]

- name: "V-38516 Low  The Reliable Datagram Sockets (RDS) protocol must be disabled unless required"
  copy: backup=no src={{ item }} dest=/etc/modprobe.d/{{ item }} owner=root group=root mode=0644
  with_items:
    - disable-rds.conf
  tags: [ 'cat3' , 'V-38516' , 'rds' , 'kernel_modules' ]

- name: V-38535 Low  The system must not respond to ICMPv4 sent to a broadcast address
  sysctl: name=net.ipv4.icmp_echo_ignore_broadcasts value=1 state=present reload=yes ignoreerrors=yes
  tags: [ 'cat3' , 'V-38535' , 'kernel_parameters' , 'network' ]

- name: V-38537 Low  The system must ignore ICMPv4 bogus error responses
  sysctl: name=net.ipv4.icmp_ignore_bogus_error_responses value=1 state=present reload=yes ignoreerrors=yes
  tags: [ 'cat3' , 'V-38537' , 'kernel_parameters' , 'network' ]

- name: V-38590 Low The system must allow locking of the console screen in text mode
  yum: name=screen state=latest
  tags: [ 'cat3' , 'V-38590' , 'screen' ]

# --- BREAK --- #

- name: V-38533 Low  The system must ignore IPv4 ICMP redirect messages.
  sysctl: name=net.ipv4.conf.default.accept_redirects value=0 state=present reload=yes ignoreerrors=yes
  tags: [ 'cat3' , 'V-38533' , 'icmp_redirects' , 'kerner_parameters' , 'network' ]

- name: Disable TCP timestamp responses
  sysctl: name=net.ipv4.tcp_timestamps value=0 state=present reload=yes ignoreerrors=yes
  tags: [ 'cat3' , 'V-38533' , 'tcp_timestamps' , 'kerner_parameters' , 'network' ]

- name: Use strong MAC algorithms
  lineinfile: "state=present backup=yes dest=/etc/ssh/sshd_config regexp='^#?MACS' line='MACS    hmac-sha1,umac-64@openssh.com,hmac-ripemd160,hmac-sha2-256,hmac-sha2-512'"
  tags: [ 'cat3' , 'ssh' , 'config' ]
  notify: restart ssh
